; Custom PHP settings
memory_limit = 1024M
upload_max_filesize = 20M
post_max_size = 21M
max_execution_time = 120
display_errors = Off
log_errors = On
log_level = error
access.log = /proc/self/fd/2
error_log = /proc/self/fd/2
error_log_format = "[%t] %e %f %l %m %r %u %a"
expose_php = Off
date.timezone = "Europe/London"
sendmail_path = "/usr/bin/msmtp -t"
